### ISSUE TITLE
Top menu transparency should be uniform

### ISSUE THREAD

**Issue by tlee21** [aetheras-io/website#1]
Currently the transparency around the menu buttons is higher than the other areas on the menu.  We should make the whole menu transparency the same.

<img width="1418" alt="Screen Shot 2019-05-13 at 4 33 48 PM" src="https://user-images.githubusercontent.com/31396515/57607311-594c5200-759d-11e9-881e-b937ef6ace5d.png">

**Comment by wuyuyu0222** [comment]
done with d0c93113ef9b2c95b580539ec37c6de771718f8f

**Comment by tlee21** [comment]
Verified on d0c93113ef9b2c95b580539ec37c6de771718f8f
