### ISSUE TITLE
[P3] the margin adjustment in the home page

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#10]
![image](https://user-images.githubusercontent.com/49321360/60337099-b2006e80-99d4-11e9-8ee6-8b50ab774873.png)
這邊圖片下面的 margin-bottom 改成 80px
目前白色區塊到灰色區塊太多了
the margin-bottom of the illustration photo reduce to 80px

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
