### ISSUE TITLE
[P2] thumbnail cards design details

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#11]
![image](https://user-images.githubusercontent.com/49321360/60337783-95fdcc80-99d6-11e9-83b0-30d3ba71dc6f.png)

這幾個 icon 我畫新的了(之前只是隨便抓的
然後這個橘色底色，左上跟右上要有跟 card 一樣的圓角

I already draw new icons
so use the new ones ↓
https://xd.adobe.com/spec/dbc0c974-a429-479e-53c0-723c95c27788-adf1/screen/3abbf277-9db0-4438-8848-45811f2cdbec/high-fi-wirefreame/
card's left-top and right-top corners should be round corners

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
