### ISSUE TITLE
[P3] the font style of the thumbnail card

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#12]
![image](https://user-images.githubusercontent.com/49321360/60337893-dbba9500-99d6-11e9-8bcd-9b77531c77e7.png)
card 裡面的文字 title 的 font-size 改成 24px，下面說明 bodyText 的 font-weight 改成 500。
因為現在看，有點沒辦法專心看內容
整個 card 的左右 padding 改成 32px

the font-size of the card's title change to 24px.
the font-weight of the bodyText change to 500.
and the card's inner padding change to 32px.
I think it would be more comfortable to read the content

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
