### ISSUE TITLE
[P3] "read the Whitepaper" btn style

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#13]
![image](https://user-images.githubusercontent.com/49321360/60338024-47046700-99d7-11e9-9936-872e5235f765.png)
---
![image](https://user-images.githubusercontent.com/49321360/60338035-508dcf00-99d7-11e9-8d04-0a40c70c822d.png)
這邊的文字跟其他按鈕一樣 letter-spacing 要改 1px。然後這個按鈕樣式我想改成單純文字右邊加上一個箭頭，hover 的時候箭頭會有左右移動的動畫(我在 mockup 上再重新調整

this btn I want to change the style
the letter-spacing change to 1px.
and discard the border, add a "→" arrow next to the words.
when hovering on the btn,  the arrow will show "left-right moving" animation

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
