### ISSUE TITLE
[P3] negative space between text area

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#14]
![image](https://user-images.githubusercontent.com/49321360/60338469-9c8d4380-99d8-11e9-8822-8e1a65669243.png)
文字應該要有左右的 margin，應該先調成36px 看看
不然的話大螢幕下看 文字實在是太長了
然後 font-size 改成 24px (同理下面的 hiring 還有 about 頁面裡的文字說明都是
文字太大有點沒辦法專心看

the negative space between the content and the container (the text area and the page) should be more 
maybe add the left-right margin of the text area by 36px
(in current version, the sentences are too long on big screen to read)
and these descriptions' font-size should change to 24px (including the "hiring" and the "culture" section's)
(the words are too large to read intently)

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91 (設定文字的max width)

**Comment by twbilldai** [comment]
didn't see the differences..
still need to modify

**Comment by wuyuyu0222** [comment]
fixed at 0483bea35294447a5cad38ec137852b1e52bc1f0

**Comment by twbilldai** [comment]
verified
