### ISSUE TITLE
[P3] font style in members content

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#15]
![image](https://user-images.githubusercontent.com/49321360/60338742-613f4480-99d9-11e9-9536-1baff65eb027.png)
---
![image](https://user-images.githubusercontent.com/49321360/60338758-6ac8ac80-99d9-11e9-822d-04c6e8ce33b9.png)
我覺得這樣比較好 所以改成這樣了
然後底色改白色 跟上面的 Our Culture 區塊做區分
詳細要看XD的spec
I think it would be better like this
and the background color will change to white
the details ↓
https://xd.adobe.com/spec/dbc0c974-a429-479e-53c0-723c95c27788-adf1/screen/2fc0ac8f-d73b-42b8-9284-06f7424e76d1/web-about/

**Comment by wuyuyu0222** [comment]
與bill討論後決定修改編排方式
![Screen Shot 2019-07-03 at 2 44 30 PM](https://user-images.githubusercontent.com/35990373/60569134-26eef200-9da1-11e9-9a98-2e7d9737a4b1.png)

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91 (按照上面討論的截圖調整)

**Comment by wuyuyu0222** [comment]
請同時檢查手機版畫面

**Comment by twbilldai** [comment]
verified
