### ISSUE TITLE
[P2] home page visual bug (mobile)

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#16]
![image](https://user-images.githubusercontent.com/49321360/60338936-d9a60580-99d9-11e9-8989-254567cf7fc0.png)
手機上看 箭頭會被瀏覽器的toolBar遮住
然後往下滑的時候 下方會出現可以左右滑動的scrollBar

the "﹀" arrow is blocked by the browser's toolBar in mobile.
and another problem is: when scrolling down, a left-right scrollBar appears at the bottom of the browser

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
