### ISSUE TITLE
[P3] sections negative space adjustment (mobile)

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#17]
![image](https://user-images.githubusercontent.com/49321360/60339016-170a9300-99da-11e9-840a-adf77484abeb.png)
這兩塊都減少個 28px 左右
I think these 2 section's negative space is too much (in mobile)
maybe reduce the height of each margin by 28px

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
