### ISSUE TITLE
[P2] members section layout (mobile)

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#18]
![image](https://user-images.githubusercontent.com/49321360/60339092-5802a780-99da-11e9-8db9-c3074dbad1a7.png)
應該要置中
the photos and words should align to center

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91 與 #15 相關

**Comment by twbilldai** [comment]
verified
