### ISSUE TITLE
[P3] menu link (mobile)

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#19]
![image](https://user-images.githubusercontent.com/49321360/60339131-7ec0de00-99da-11e9-8349-e6704ce28216.png)
感覺這邊 Logo 要能點回首頁
如果我現在在 about 頁面 我就沒有東西可以點回首頁 要先關掉 menu 再點 Logo

I think the Aetheras logo here should link to the home page
in the current version, when I'm in the "about" page, I tap the menu btn and there is no link to the home page. I have to close the menu and then tap the logo to go back to home page.

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
