### ISSUE TITLE
Changing the current language should not trigger auto-scrolling

### ISSUE THREAD

**Issue by tlee21** [aetheras-io/website#2]
Auto-scrolling is being triggered sometimes if a menu item is previously clicked.

1. Click on a link on the top menu, such as "Agora"
2. Scroll down on the page.
3. Switch the current language of the page.  Ex. from English to Chinese

Result:
The page auto scrolls to the Agora section.

**Comment by wuyuyu0222** [comment]
fixed 12cf235e89588be2da00863f884d613526139a20

**Comment by tlee21** [comment]
It's auto-scrolling again at ad26a3869babdc46925cf45b37dc2be2880cab8c

**Comment by wuyuyu0222** [comment]
fixed please check again 837c4c336614cc814d4e2e11be4f244fb4b2a92d

**Comment by tlee21** [comment]
Verified on 837c4c336614cc814d4e2e11be4f244fb4b2a92d
