### ISSUE TITLE
[P2] favicon 

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#20]
![image](https://user-images.githubusercontent.com/49321360/60339328-13c3d700-99db-11e9-81ad-bc7d6bbf3dfc.png)

要改成新的
use the new favicon
the file I already send to Jake.
it can also be found on google drive ↓
Company Public > Branding Assets > logo-simplify-icon > aetheras_favicon_64x64px.ico

![image](https://user-images.githubusercontent.com/49321360/60339361-2807d400-99db-11e9-85c9-81c4a008bd3c.png)

**Comment by tlee21** [comment]
Upgrading this to a P2

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
