### ISSUE TITLE
change the font size and align to left

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#23]
![image](https://user-images.githubusercontent.com/49321360/64321542-4e597980-cff3-11e9-9ab7-4cb021d0c54b.png)

like this
and cancel the "font-style: italic;"

**Comment by tlee21** [comment]
@twbilldai  
What's the gray color that we want?

**Comment by tlee21** [comment]
> @twbilldai
> What's the gray color that we want?
From slack:
#949291

**Comment by twbilldai** [comment]
verified
