### ISSUE TITLE
Links to a section of page is removing its hash part after a second

### ISSUE THREAD

**Issue by tlee21** [aetheras-io/website#3]
1. Launch the website
2. Click on the News link on the top menu.

Result:

Notice that the url is
http://localhost:3000/#news

And then after a moment, it becomes
http://localhost:3000/

This behavior messes with the browser's back button functionality, preventing the user from going back to the previous page.

**Comment by wuyuyu0222** [comment]
fixed at 8a130160ed9e6ea9b40faae49f2b81cf767316a2

**Comment by tlee21** [comment]
Verified at ad26a3869babdc46925cf45b37dc2be2880cab8c
