### ISSUE TITLE
Error when clicking News from the About Page

### ISSUE THREAD

**Issue by tlee21** [aetheras-io/website#4]
Repros on 837c4c336614cc814d4e2e11be4f244fb4b2a92d

1. Launch the website
2. Click on the "News" link from the top menu

Result:
The following error is shown:

TypeError: Cannot read property 'scrollIntoView' of null

![image](https://user-images.githubusercontent.com/31396515/58069997-f58fdd80-7bc9-11e9-9405-c5b9e1481f0f.png)

**Comment by wuyuyu0222** [comment]
fixed at  6fb9eb23db6b504083dd88f8840987561dc9199e

**Comment by tlee21** [comment]
Verified on 6fb9eb23db6b504083dd88f8840987561dc9199e
