### ISSUE TITLE
Need to resize buttons to fit the text

### ISSUE THREAD

**Issue by tlee21** [aetheras-io/website#6]
Some buttons need to be resized after filling in the text.

For example:

![image](https://user-images.githubusercontent.com/31396515/60170945-189e5480-983c-11e9-9da0-780a6894b1b9.png)

Buttons that need resizing:
Front page:
- 2 Learn mores
- Read the Whitepaper

**Comment by wuyuyu0222** [comment]
fixed at f409fed07c150c7d09cec68e6c79370ffc215be1

**Comment by tlee21** [comment]
Verified at 40695370b8447a4060f4734ef591b0a31878cc12
