### ISSUE TITLE
[P3] the whole page's negative space

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#7]
![FireShot Capture 016 - Aetheras - aetheras-io web app](https://user-images.githubusercontent.com/49321360/60336308-8b413880-99d2-11e9-897d-37366e9f363f.png)

整個頁面內容的container(包括navBar)應該要縮短(像 polkadot 那樣，可能是固定的 max-width
因為網站內容也不是很多，在大螢幕(1920*1080)的時候，東西都好大

the page's container should be narrower (like Polkadot, maybe it's fixed max-width when the device-width is large)
(in the current version, the stuff in our website is too big when it's on big screen (1920*1080). but our contents are not so many, so it's kinda weird) 

---
![FireShot Capture 017 - Polkadot_ Decentralized Web 3 0 Blockchain Interoperability Platform_ - polkadot network](https://user-images.githubusercontent.com/49321360/60336355-af9d1500-99d2-11e9-966e-11f348ff6111.png)

**Comment by twbilldai** [comment]
網站的favicon要改

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by wuyuyu0222** [comment]
fixed with title align at 898778e5086af087ca643ba3d4d1561eab4842d6

**Comment by twbilldai** [comment]
verified
