### ISSUE TITLE
[P3] hover status of the navBar

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#8]
![image](https://user-images.githubusercontent.com/49321360/60336769-d445bc80-99d3-11e9-8441-c099167cf98b.png)
navBar裡的textBtn hover的時候要變橘色(主色)

the hover status of the textBtn in navBar should change to orange (primary color)

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
