### ISSUE TITLE
[P3] main btn details

### ISSUE THREAD

**Issue by twbilldai** [aetheras-io/website#9]
![image](https://user-images.githubusercontent.com/49321360/60336990-69e14c00-99d4-11e9-8ed8-970ce7104df8.png)
按鈕裡面的文字 letter-spacing 改成 1px
目前字距太多了

the words' letter-spacing of the btn change to 1px
I think it would be better

**Comment by wuyuyu0222** [comment]
fixed at 60545cfa58c62f2bf2133f71aa0cfa392412bb91

**Comment by twbilldai** [comment]
verified
